name: "Build Trunk"

on:
  push:
    branches:
      - trunk

jobs:
  buildTag:
    name: Build Tag
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Build Image
        run: JAVA_HOME=/opt/graalvm mvn clean package

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: kyberorg/hello-world-action:trunk

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
